apiVersion: v1
kind: Namespace
metadata:
  name: pranit

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: auth-app
  namespace: pranit 
spec:
  containers:
    - name: my-cont
      image: httpd
      ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: pod-svc
  namespace: pranit
spec:
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: auth-app
      